package ifneeded vessel::bsd 1.0.0 [list source [file join $dir bsd.tcl]]
package ifneeded vessel::build 1.0.0 [list source [file join $dir build.tcl]]
package ifneeded vesseld::client 1.0.0 [list source [file join $dir vesseld_client.tcl]]
package ifneeded vessel::definition_file 1.0.0 [list source [file join $dir definition_file.tcl]]
package ifneeded vessel::deploy 1.0.0 [list source [file join $dir deploy.tcl]]
package ifneeded vessel::dns 1.0.0 [list source [file join $dir dns dns.tcl]]
package ifneeded vessel::env 1.0.0 [list source [file join $dir environment.tcl]]
package ifneeded vessel::export 1.0.0 [list source [file join $dir export.tcl]]
package ifneeded vessel::import 1.0.0 [list source [file join $dir import.tcl]]
package ifneeded vessel::jail 1.0.0 [list source [file join $dir jail.tcl]]
package ifneeded vessel::metadata_db 1.0.0 [list source [file join $dir metadata_db.tcl]]
package ifneeded vessel::name-gen 1.0.0 [list source [file join $dir name-gen.tcl]]
package ifneeded vessel::native 1.0.0 [list load [file join $dir libvesseltcl.so]]
package ifneeded vesselsqlite3 3.42.0 [list load [file join $dir libvesselsqlite.so]]
package ifneeded vessel::network 1.0.0 [list source [file join $dir network.tcl]]
package ifneeded vessel::pty_shell 1.0.0 [list source [file join $dir pty_shell.tcl]]
package ifneeded vessel::repo 1.0.0 [list source [file join $dir repos.tcl]]
package ifneeded vessel::run 1.0.0 [list source [file join $dir run.tcl]]
package ifneeded vessel::syslog 1.0.0 [list source [file join $dir syslog.tcl]]
package ifneeded vessel::zfs 1.0.0 [list source [file join $dir zfs.tcl]]

package ifneeded VesselFileCommands 1.0.0 [list source [file join $dir vessel_file_commands.tcl]]
